global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "user-api"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["api-user:8080"]
        labels:
          app: "user-api"
          env: "local"
    relabel_configs:
      - target_label: instance
        replacement: "user-api"

  - job_name: "admin-api"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["api-admin:8081"]
        labels:
          app: "admin-api"
          env: "local"
    relabel_configs:
      - target_label: instance
        replacement: "admin-api"

  - job_name: "transcoder"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["transcoder:8082"]
        labels:
          app: "transcoder"
          env: "local"
    relabel_configs:
      - target_label: instance
        replacement: "transcoder"
